#!/usr/bin/env bash
# shellcheck disable=SC2016

# MIT license (c) 2024 https://github.com/slowpeek
# Homepage: https://github.com/slowpeek/kubuntu-2404-fixes

CONF=~/.config/plasma-org.kde.plasma.desktop-appletsrc
[[ -e $CONF ]] || exit 0

del_key() {
    kwriteconfig5 --file "$CONF" --group Containments --group "$1" --key "$2" --delete ''
}

cont_id=
while read -r line; do
    if [[ $line =~ \[Containments\]\[([0-9]+)\] ]]; then
        while [[ -n $line ]]; do
            read -r line
            if [[ $line == 'plugin=org.kde.plasma.private.systemtray' ]]; then
                cont_id=${BASH_REMATCH[1]}
                break 2
            fi
        done
    fi
done < "$CONF"

if [[ -n $cont_id ]]; then
    del_key "$cont_id" popupWidth
    del_key "$cont_id" popupHeight
fi
